name: Airflow Setting CI

on:
  push:
    paths: 
      - 'docker-compose.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: copy files and run docker compose
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          git remote set-url origin git@github.com:${{ secrets.USERNAME_GITHUB }}/Stocks_ProJ.git
          git pull origin main
          
 