name: Airflow Setting CI

on:
  push:
    paths: 
      - 'docker-compose.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: copy docker compose to ec2 server and run docker compose
      uses: appleboy/ssh-action@master
      with: 
        key: ${{ secrets.KEY }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: 22
        script: |
          whoami