name: Airflow Setting CI

on:
  push:
    paths: 
      - 'docker-compose.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create SSH Key
      run: |
        echo "${{ secrets.KEY }}" > ~/private-key.pem
        chmod 600 ~/private-key.pem
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Copy files to remote server
      run: |
        cd ${{ github.workspace }}
        scp -i ~/private-key.pem docker-compose.yaml ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.AIRFLOW_PATH }}/docker-compose.yaml
        scp -i ~/private-key.pem -r ./Dags ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.AIRFLOW_PATH }}/dags
        scp -i ~/private-key.pem -r ./test ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.AIRFLOW_PATH }}/test
      

          
 